name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: "https://registry.npmjs.org"

    - name: install pnpm
      shell: bash
      run: npm i pnpm@latest -g

    - name: setup pnpm config
      shell: bash
      run: pnpm config set store-dir $PNPM_CACHE_FOLDER

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "maxwell.multinite@gmail.com"
        git config --global user.name "Multinite"

    - name: Install dependencies
      shell: bash
      run: pnpm install
