name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Build
        run: |
          cd packages/MultiUI
          npm run build:prod

      - name: Dir
        run: pwd

      - name: Tests
        run: npm run test

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          title: "ci(changesets): :package: version packages"
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Sync files from canary to main branch if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   run: |
      #     curl -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #       https://api.github.com/repos/owner/repo/dispatches \
      #       -d '{"event_type":"sync-canary-to-main"}'

      # - name: Create canary release
      #   if: steps.changesets.outputs.published != 'true'
      #   run: |
      #     git checkout canary
      #     npm run version:canary
      #     pnpm release:canary
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
